// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3kBY-XAiduhS3Y-Jdv9BUBp824ZDk-CY',
    appId: '1:558322946404:web:bec94b60f79bc595b96a71',
    messagingSenderId: '558322946404',
    projectId: 'nirogisathi-ebc17',
    authDomain: 'nirogisathi-ebc17.firebaseapp.com',
    storageBucket: 'nirogisathi-ebc17.firebasestorage.app',
    measurementId: 'G-C2TCT5DWGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDEHBDnwrUjP8TsXycJKgPi_jcfgxoITc',
    appId: '1:558322946404:android:882145b87e0ddc3eb96a71',
    messagingSenderId: '558322946404',
    projectId: 'nirogisathi-ebc17',
    storageBucket: 'nirogisathi-ebc17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDah24qNsRBx9erv9KxsXvFA14eCwWNR6o',
    appId: '1:558322946404:ios:bc01ee6c2677e1d5b96a71',
    messagingSenderId: '558322946404',
    projectId: 'nirogisathi-ebc17',
    storageBucket: 'nirogisathi-ebc17.firebasestorage.app',
    iosBundleId: 'com.nirogisathi.nirogisathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDah24qNsRBx9erv9KxsXvFA14eCwWNR6o',
    appId: '1:558322946404:ios:bc01ee6c2677e1d5b96a71',
    messagingSenderId: '558322946404',
    projectId: 'nirogisathi-ebc17',
    storageBucket: 'nirogisathi-ebc17.firebasestorage.app',
    iosBundleId: 'com.nirogisathi.nirogisathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3kBY-XAiduhS3Y-Jdv9BUBp824ZDk-CY',
    appId: '1:558322946404:web:6f69612c3bf0fcf8b96a71',
    messagingSenderId: '558322946404',
    projectId: 'nirogisathi-ebc17',
    authDomain: 'nirogisathi-ebc17.firebaseapp.com',
    storageBucket: 'nirogisathi-ebc17.firebasestorage.app',
    measurementId: 'G-LWBLSC7SZW',
  );
}
